import type { Infer } from "convex/values";
import type { vItemAttributes } from "./validators";

/**
 * The Nyoni capsule: the 39 pieces every member's wardrobe starts with, enough to dress a
 * boardroom, a wedding, a black-tie dinner and a Saturday. GENERATED by scripts/build-collection.mjs
 * from research/nyoni/woo-products.json on 2026-09-23; choose the pieces in that
 * script's CAPSULE list, not here. `key` is stable across syncs (it is what `items.collectionKey` stores);
 * a piece whose image cannot be fetched is skipped by the seeder rather than failing the whole seed, and a
 * member's item whose key has left the capsule is retired on their next seed.
 */
export type CollectionPiece = {
  key: string;
  productUrl: string;
  /** What the piece costs on its own. Absent when it is only sold as part of something. */
  priceUsd?: number;
  /** Set on a suit's jacket, trousers and waistcoat: the suit they are sold as, and its price. */
  partOf?: { name: string; priceUsd: number };
  image: string;
  attributes: Infer<typeof vItemAttributes>;
};

export const COLLECTION: readonly CollectionPiece[] = [
  // Suits
  {
    key: "nyoni-nathan-jacket",
    productUrl: "https://nyonicouture.com/product/three-piece-suit/nathan/",
    partOf: { name: "Midnight Navy Three Piece Suit", priceUsd: 895 },
    image: "/collection/nyoni-nathan-jacket.webp",
    attributes: {
      name: "Midnight Navy Suit Jacket",
      category: "outerwear",
      subcategory: "suit jacket",
      colours: { primary: "navy", secondary: [], hex: ["#1F2A44"] },
      pattern: "solid",
      material: "wool",
      season: ["autumn", "winter", "spring"],
      formality: "formal",
      fit: "slim",
      brand: "Nyoni Couture",
      description:
        "The three-piece suit built on the most authoritative colour in menswear. The Nyoni Midnight Navy Three Piece Suit delivers the complete construction statement of three-piece dressing in a deep midnight navy Super 200s wool — single breasted…",
    },
  },
  {
    key: "nyoni-nathan-trousers",
    productUrl: "https://nyonicouture.com/product/three-piece-suit/nathan/",
    partOf: { name: "Midnight Navy Three Piece Suit", priceUsd: 895 },
    image: "/collection/nyoni-nathan-trousers.webp",
    attributes: {
      name: "Midnight Navy Suit Trousers",
      category: "bottom",
      subcategory: "suit trousers",
      colours: { primary: "navy", secondary: [], hex: ["#1F2A44"] },
      pattern: "solid",
      material: "wool",
      season: ["autumn", "winter", "spring"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "The three-piece suit built on the most authoritative colour in menswear. The Nyoni Midnight Navy Three Piece Suit delivers the complete construction statement of three-piece dressing in a deep midnight navy Super 200s wool — single breasted…",
    },
  },
  {
    key: "nyoni-nathan-vest",
    productUrl: "https://nyonicouture.com/product/three-piece-suit/nathan/",
    partOf: { name: "Midnight Navy Three Piece Suit", priceUsd: 895 },
    image: "/collection/nyoni-nathan-vest.webp",
    attributes: {
      name: "Midnight Navy Waistcoat",
      category: "vest",
      subcategory: "waistcoat",
      colours: { primary: "navy", secondary: [], hex: ["#1F2A44"] },
      pattern: "solid",
      material: "wool",
      season: ["autumn", "winter", "spring"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "The three-piece suit built on the most authoritative colour in menswear. The Nyoni Midnight Navy Three Piece Suit delivers the complete construction statement of three-piece dressing in a deep midnight navy Super 200s wool — single breasted…",
    },
  },
  {
    key: "nyoni-grayson-jacket",
    productUrl: "https://nyonicouture.com/product/three-piece-suit/grayson/",
    partOf: { name: "Charcoal Three Piece Suit", priceUsd: 895 },
    image: "/collection/nyoni-grayson-jacket.webp",
    attributes: {
      name: "Charcoal Suit Jacket",
      category: "outerwear",
      subcategory: "suit jacket",
      colours: { primary: "charcoal", secondary: [], hex: ["#3A3A3A"] },
      pattern: "solid",
      material: "wool",
      season: ["autumn", "winter", "spring"],
      formality: "formal",
      fit: "slim",
      brand: "Nyoni Couture",
      description:
        "The three-piece suit that works everywhere and apologises to no one. The Nyoni Charcoal Three Piece Suit delivers the complete construction authority of three-piece dressing in deep charcoal Super 200s wool — single breasted notch lapel…",
    },
  },
  {
    key: "nyoni-grayson-trousers",
    productUrl: "https://nyonicouture.com/product/three-piece-suit/grayson/",
    partOf: { name: "Charcoal Three Piece Suit", priceUsd: 895 },
    image: "/collection/nyoni-grayson-trousers.webp",
    attributes: {
      name: "Charcoal Suit Trousers",
      category: "bottom",
      subcategory: "suit trousers",
      colours: { primary: "charcoal", secondary: [], hex: ["#3A3A3A"] },
      pattern: "solid",
      material: "wool",
      season: ["autumn", "winter", "spring"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "The three-piece suit that works everywhere and apologises to no one. The Nyoni Charcoal Three Piece Suit delivers the complete construction authority of three-piece dressing in deep charcoal Super 200s wool — single breasted notch lapel…",
    },
  },
  {
    key: "nyoni-grayson-vest",
    productUrl: "https://nyonicouture.com/product/three-piece-suit/grayson/",
    partOf: { name: "Charcoal Three Piece Suit", priceUsd: 895 },
    image: "/collection/nyoni-grayson-vest.webp",
    attributes: {
      name: "Charcoal Waistcoat",
      category: "vest",
      subcategory: "waistcoat",
      colours: { primary: "charcoal", secondary: [], hex: ["#3A3A3A"] },
      pattern: "solid",
      material: "wool",
      season: ["autumn", "winter", "spring"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "The three-piece suit that works everywhere and apologises to no one. The Nyoni Charcoal Three Piece Suit delivers the complete construction authority of three-piece dressing in deep charcoal Super 200s wool — single breasted notch lapel…",
    },
  },
  {
    key: "nyoni-evano-windowpane-jacket",
    productUrl: "https://nyonicouture.com/product/three-piece-suit/evano-windowpane/",
    partOf: { name: "Evano Windowpane", priceUsd: 895 },
    image: "/collection/nyoni-evano-windowpane-jacket.webp",
    attributes: {
      name: "Evano Windowpane Suit Jacket",
      category: "outerwear",
      subcategory: "suit jacket",
      colours: { primary: "grey", secondary: [], hex: ["#7D7B76"] },
      pattern: "solid",
      material: "wool",
      season: ["autumn", "winter", "spring"],
      formality: "formal",
      fit: "slim",
      brand: "Nyoni Couture",
      description:
        "Super 200s wool in a grey windowpane check, for the days a plain suit is too plain. The waistcoat makes it a wedding; without it, a Tuesday.",
    },
  },
  {
    key: "nyoni-evano-windowpane-trousers",
    productUrl: "https://nyonicouture.com/product/three-piece-suit/evano-windowpane/",
    partOf: { name: "Evano Windowpane", priceUsd: 895 },
    image: "/collection/nyoni-evano-windowpane-trousers.webp",
    attributes: {
      name: "Evano Windowpane Suit Trousers",
      category: "bottom",
      subcategory: "suit trousers",
      colours: { primary: "grey", secondary: [], hex: ["#7D7B76"] },
      pattern: "solid",
      material: "wool",
      season: ["autumn", "winter", "spring"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Super 200s wool in a grey windowpane check, for the days a plain suit is too plain. The waistcoat makes it a wedding; without it, a Tuesday.",
    },
  },
  {
    key: "nyoni-evano-windowpane-vest",
    productUrl: "https://nyonicouture.com/product/three-piece-suit/evano-windowpane/",
    partOf: { name: "Evano Windowpane", priceUsd: 895 },
    image: "/collection/nyoni-evano-windowpane-vest.webp",
    attributes: {
      name: "Evano Windowpane Waistcoat",
      category: "vest",
      subcategory: "waistcoat",
      colours: { primary: "grey", secondary: [], hex: ["#7D7B76"] },
      pattern: "solid",
      material: "wool",
      season: ["autumn", "winter", "spring"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Super 200s wool in a grey windowpane check, for the days a plain suit is too plain. The waistcoat makes it a wedding; without it, a Tuesday.",
    },
  },
  {
    key: "nyoni-opel-black-tux-jacket",
    productUrl: "https://nyonicouture.com/product/tuxedo/opel-black-tux/",
    partOf: { name: "Sovereign Black Double-Breasted Tuxedo", priceUsd: 895 },
    image: "/collection/nyoni-opel-black-tux-jacket.webp",
    attributes: {
      name: "Sovereign Black Double-Breasted Tuxedo Jacket",
      category: "outerwear",
      subcategory: "suit jacket",
      colours: { primary: "black", secondary: [], hex: ["#141414"] },
      pattern: "solid",
      material: "wool",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      fit: "slim",
      brand: "Nyoni Couture",
      description:
        "No pattern, no distraction just structure. This double-breasted tuxedo leans entirely on the cut: a satin peak lapel, a six-button front, and a shoulder line built to hold its shape all night.",
    },
  },
  {
    key: "nyoni-opel-black-tux-trousers",
    productUrl: "https://nyonicouture.com/product/tuxedo/opel-black-tux/",
    partOf: { name: "Sovereign Black Double-Breasted Tuxedo", priceUsd: 895 },
    image: "/collection/nyoni-opel-black-tux-trousers.webp",
    attributes: {
      name: "Sovereign Black Double-Breasted Tuxedo Trousers",
      category: "bottom",
      subcategory: "suit trousers",
      colours: { primary: "black", secondary: [], hex: ["#141414"] },
      pattern: "solid",
      material: "wool",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "No pattern, no distraction just structure. This double-breasted tuxedo leans entirely on the cut: a satin peak lapel, a six-button front, and a shoulder line built to hold its shape all night.",
    },
  },
  {
    key: "nyoni-perseo-jacket",
    productUrl: "https://nyonicouture.com/product/double-breasted/perseo/",
    partOf: { name: "Dove Gray Herringbone Double Breast Suit", priceUsd: 985 },
    image: "/collection/nyoni-perseo-jacket.webp",
    attributes: {
      name: "Dove Gray Herringbone Double Breast Suit Jacket",
      category: "outerwear",
      subcategory: "suit jacket",
      colours: { primary: "grey", secondary: [], hex: ["#7D7B76"] },
      pattern: "solid",
      material: "wool",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      fit: "slim",
      brand: "Nyoni Couture",
      description:
        "The DB suit that belongs everywhere. The Nyoni Dove Gray Herringbone Double Breast Suit arrives in a clean mid silver-grey that delivers the double breasted silhouette at its most versatile — Super 110s–200s wool, wide peak lapels, a 6×2…",
    },
  },
  {
    key: "nyoni-perseo-trousers",
    productUrl: "https://nyonicouture.com/product/double-breasted/perseo/",
    partOf: { name: "Dove Gray Herringbone Double Breast Suit", priceUsd: 985 },
    image: "/collection/nyoni-perseo-trousers.webp",
    attributes: {
      name: "Dove Gray Herringbone Double Breast Suit Trousers",
      category: "bottom",
      subcategory: "suit trousers",
      colours: { primary: "grey", secondary: [], hex: ["#7D7B76"] },
      pattern: "solid",
      material: "wool",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "The DB suit that belongs everywhere. The Nyoni Dove Gray Herringbone Double Breast Suit arrives in a clean mid silver-grey that delivers the double breasted silhouette at its most versatile — Super 110s–200s wool, wide peak lapels, a 6×2…",
    },
  },

  // Blazers
  {
    key: "nyoni-navy-aztec-blazer",
    productUrl: "https://nyonicouture.com/product/blazers/navy-aztec-blazer/",
    priceUsd: 495,
    image: "/collection/nyoni-navy-aztec-blazer.webp",
    attributes: {
      name: "Indigo Jacquard Tailored Blazer",
      category: "outerwear",
      subcategory: "blazer",
      colours: { primary: "navy", secondary: [], hex: ["#1F2A44"] },
      pattern: "check",
      material: "wool",
      season: ["spring", "autumn", "winter"],
      formality: "smart-casual",
      fit: "slim",
      brand: "Nyoni Couture",
      description:
        "Texture is the new power move. The Nyoni Indigo Jacquard Tailored Blazer takes the authority of a navy blazer and elevates it with a rich tonal jacquard micro-check weave that catches the light and holds the eye.",
    },
  },
  {
    key: "nyoni-vicenzo",
    productUrl: "https://nyonicouture.com/product/blazers/vicenzo/",
    priceUsd: 895,
    image: "/collection/nyoni-vicenzo.webp",
    attributes: {
      name: "Vicenzo Blazer",
      category: "outerwear",
      subcategory: "blazer",
      colours: { primary: "grey", secondary: [], hex: ["#7D7B76"] },
      pattern: "solid",
      material: "wool",
      season: ["spring", "autumn", "winter"],
      formality: "smart-casual",
      fit: "slim",
      brand: "Nyoni Couture",
      description:
        "A grey mélange odd jacket with enough texture to read as tailoring rather than a suit jacket gone astray. Takes the taupe or walnut trousers.",
    },
  },
  {
    key: "nyoni-james-blazer",
    productUrl: "https://nyonicouture.com/product/blazers/james-blazer/",
    priceUsd: 1095,
    image: "/collection/nyoni-james-blazer.webp",
    attributes: {
      name: "James Blazer",
      category: "outerwear",
      subcategory: "blazer",
      colours: { primary: "grey", secondary: [], hex: ["#7D7B76"] },
      pattern: "solid",
      material: "wool",
      season: ["spring", "autumn", "winter"],
      formality: "smart-casual",
      fit: "slim",
      brand: "Nyoni Couture",
      description:
        "Grey-green glen check with a soft windowpane over it. The jacket for a town day that is not quite a suit day.",
    },
  },
  {
    key: "nyoni-thomson-blazer",
    productUrl: "https://nyonicouture.com/product/blazers/thomson-blazer/",
    priceUsd: 1095,
    image: "/collection/nyoni-thomson-blazer.webp",
    attributes: {
      name: "Thomson Blazer",
      category: "outerwear",
      subcategory: "blazer",
      colours: { primary: "orange", secondary: [], hex: ["#C7791E"] },
      pattern: "solid",
      material: "wool",
      season: ["spring", "autumn", "winter"],
      formality: "smart-casual",
      fit: "slim",
      brand: "Nyoni Couture",
      description:
        "Burnt ochre in an open weave, cut unstructured. Summer, and the one piece in the capsule that answers a navy trouser with warmth.",
    },
  },
  {
    key: "nyoni-ivoire-blazer-2",
    productUrl: "https://nyonicouture.com/product/blazers/ivoire-blazer-2/",
    priceUsd: 495,
    image: "/collection/nyoni-ivoire-blazer-2.webp",
    attributes: {
      name: "Ivoire Double-Breasted Blazer",
      category: "outerwear",
      subcategory: "blazer",
      colours: { primary: "ivory", secondary: [], hex: ["#F4EFE6"] },
      pattern: "solid",
      material: "wool",
      season: ["spring", "autumn", "winter"],
      formality: "smart-casual",
      fit: "slim",
      brand: "Nyoni Couture",
      description:
        "Ivory, double breasted, peak lapel. It carries a black tie evening in summer and a wedding at any time of year.",
    },
  },

  // Trousers
  {
    key: "nyoni-classic-side-adjuster-dress-pants",
    productUrl: "https://nyonicouture.com/product/trousers/nyoni-classic-side-adjuster-dress-pants/",
    priceUsd: 195,
    image: "/collection/nyoni-classic-side-adjuster-dress-pants.webp",
    attributes: {
      name: "Classic Side Adjuster Dress Pants",
      category: "bottom",
      subcategory: "dress trousers",
      colours: { primary: "black", secondary: [], hex: ["#141414"] },
      pattern: "solid",
      material: "wool",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "A timeless wardrobe essential, these Classic Black Side Adjuster Dress Pants are expertly tailored for the modern gentleman. Crafted from premium suiting fabric, they feature a sleek flat-front design with elegant side adjusters, creating a…",
    },
  },
  {
    key: "nyoni-taupe-flat-front-tailored-dress-pants",
    productUrl: "https://nyonicouture.com/product/trousers/nyoni-taupe-flat-front-tailored-dress-pants/",
    priceUsd: 265,
    image: "/collection/nyoni-taupe-flat-front-tailored-dress-pants.webp",
    attributes: {
      name: "Taupe Flat Front Tailored Dress Pants",
      category: "bottom",
      subcategory: "dress trousers",
      colours: { primary: "taupe", secondary: [], hex: ["#B3A492"] },
      pattern: "solid",
      material: "wool",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Refined, versatile, and effortlessly sophisticated, these Taupe Flat Front Tailored Dress Pants are a timeless essential for every modern gentleman’s wardrobe.",
    },
  },
  {
    key: "nyoni-midnight-glen-plaid-pant",
    productUrl: "https://nyonicouture.com/product/trousers/nyoni-midnight-glen-plaid-pant/",
    priceUsd: 195,
    image: "/collection/nyoni-midnight-glen-plaid-pant.webp",
    attributes: {
      name: "Midnight Glen Plaid Pant",
      category: "bottom",
      subcategory: "dress trousers",
      colours: { primary: "navy", secondary: [], hex: ["#1F2A44"] },
      pattern: "glen plaid",
      material: "wool",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Nyoni Midnight Glen Plaid Trousers feature a stylish plaid design with a comfortable fit, ideal for versatile wear in both formal and casual settings.",
    },
  },
  {
    key: "nyoni-walnut-tweed-pant",
    productUrl: "https://nyonicouture.com/product/trousers/nyoni-walnut-tweed-pant/",
    priceUsd: 195,
    image: "/collection/nyoni-walnut-tweed-pant.webp",
    attributes: {
      name: "Walnut Tweed Pant",
      category: "bottom",
      subcategory: "dress trousers",
      colours: { primary: "brown", secondary: [], hex: ["#5A3A24"] },
      pattern: "solid",
      material: "wool",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Nyoni Walnut Tweed Pant combines luxurious tweed fabric with a classic design, offering a comfortable fit ideal for both formal and casual settings.",
    },
  },
  {
    key: "nyoni-black-satin-side-stripe-tuxedo-pants",
    productUrl: "https://nyonicouture.com/product/trousers/nyoni-black-satin-side-stripe-tuxedo-pants/",
    priceUsd: 225,
    image: "/collection/nyoni-black-satin-side-stripe-tuxedo-pants.webp",
    attributes: {
      name: "Black Satin Side Stripe Tuxedo Pants",
      category: "bottom",
      subcategory: "dress trousers",
      colours: { primary: "black", secondary: [], hex: ["#141414"] },
      pattern: "stripe",
      material: "wool",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Complete your formal look with these Black Satin Side Stripe Tuxedo Pants , expertly tailored for timeless sophistication. Crafted from premium suiting fabric, these trousers feature elegant satin side stripes and a matching satin…",
    },
  },

  // Vests
  {
    key: "nyoni-chalcedony",
    productUrl: "https://nyonicouture.com/product/accessories/vest/chalcedony/",
    priceUsd: 225,
    image: "/collection/nyoni-chalcedony.webp",
    attributes: {
      name: "Chalcedony Shawl Waistcoat",
      category: "vest",
      subcategory: "waistcoat",
      colours: { primary: "charcoal", secondary: [], hex: ["#3A3A3A"] },
      pattern: "solid",
      material: "wool",
      season: ["autumn", "winter", "spring"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "A charcoal shawl waistcoat, plain: the one that goes under every jacket in the capsule without asking a question.",
    },
  },
  {
    key: "nyoni-kenzie",
    productUrl: "https://nyonicouture.com/product/accessories/vest/kenzie/",
    priceUsd: 186,
    image: "/collection/nyoni-kenzie.webp",
    attributes: {
      name: "Kenzie Waistcoat",
      category: "vest",
      subcategory: "waistcoat",
      colours: { primary: "navy", secondary: [], hex: ["#1F2A44"] },
      pattern: "solid",
      material: "wool",
      season: ["autumn", "winter", "spring"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "A navy wool waistcoat for separates: over the blue shirt with grey or taupe trousers, or under a blazer when the evening turns formal.",
    },
  },
  {
    key: "nyoni-yuma",
    productUrl: "https://nyonicouture.com/product/accessories/vest/yuma/",
    priceUsd: 225,
    image: "/collection/nyoni-yuma.webp",
    attributes: {
      name: "Yuma Double-Breasted Waistcoat",
      category: "vest",
      subcategory: "waistcoat",
      colours: { primary: "grey", secondary: [], hex: ["#7D7B76"] },
      pattern: "solid",
      material: "wool",
      season: ["autumn", "winter", "spring"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Mid grey, double breasted, shawl collar. A waistcoat with a front of its own, worn best where the jacket comes off.",
    },
  },
  {
    key: "nyoni-hematite",
    productUrl: "https://nyonicouture.com/product/accessories/vest/hematite/",
    priceUsd: 225,
    image: "/collection/nyoni-hematite.webp",
    attributes: {
      name: "Hematite Windowpane Waistcoat",
      category: "vest",
      subcategory: "waistcoat",
      colours: { primary: "blue", secondary: [], hex: ["#3B6EA8"] },
      pattern: "solid",
      material: "wool",
      season: ["autumn", "winter", "spring"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Blue with a fine windowpane. It lifts a plain charcoal or navy suit without competing with a patterned jacket.",
    },
  },
  {
    key: "nyoni-gabbro",
    productUrl: "https://nyonicouture.com/product/accessories/vest/gabbro/",
    priceUsd: 225,
    image: "/collection/nyoni-gabbro.webp",
    attributes: {
      name: "Gabbro Marbled Waistcoat",
      category: "vest",
      subcategory: "waistcoat",
      colours: { primary: "black", secondary: [], hex: ["#141414"] },
      pattern: "solid",
      material: "wool",
      season: ["autumn", "winter", "spring"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "A marbled black and ivory waistcoat. Black tie, and nothing else: it wants the plainest jacket in the room.",
    },
  },

  // Boots
  {
    key: "nyoni-antwerp-wing-tip",
    productUrl: "https://nyonicouture.com/product/boots/antwerp-wing-tip/",
    priceUsd: 495,
    image: "/collection/nyoni-antwerp-wing-tip.webp",
    attributes: {
      name: "Antwerp Wing-Tip Boot",
      category: "shoes",
      subcategory: "boots",
      colours: { primary: "brown", secondary: [], hex: ["#5A3A24"] },
      pattern: "solid",
      material: "calfskin",
      season: ["autumn", "winter", "spring"],
      formality: "smart-casual",
      brand: "Nyoni Couture",
      description:
        "Cognac calf with a buttoned side and a wing-tip toe, made in Italy on a leather sole. The boot for brown and taupe tailoring.",
    },
  },
  {
    key: "nyoni-roma-wing-tip",
    productUrl: "https://nyonicouture.com/product/boots/roma-wing-tip/",
    priceUsd: 495,
    image: "/collection/nyoni-roma-wing-tip.webp",
    attributes: {
      name: "Roma Wing-Tip Boot",
      category: "shoes",
      subcategory: "boots",
      colours: { primary: "black", secondary: [], hex: ["#141414"] },
      pattern: "solid",
      material: "suede",
      season: ["autumn", "winter", "spring"],
      formality: "smart-casual",
      brand: "Nyoni Couture",
      description:
        "Black calf and suede, laced, on a leather sole, made in Italy. The most forgiving boot here with a checked or textured suit.",
    },
  },
  {
    key: "nyoni-monaco-cap-toe",
    productUrl: "https://nyonicouture.com/product/boots/monaco-cap-toe/",
    priceUsd: 550,
    image: "/collection/nyoni-monaco-cap-toe.webp",
    attributes: {
      name: "Monaco Cap-Toe Boot",
      category: "shoes",
      subcategory: "boots",
      colours: { primary: "black", secondary: [], hex: ["#141414"] },
      pattern: "solid",
      material: "suede",
      season: ["autumn", "winter", "spring"],
      formality: "smart-casual",
      brand: "Nyoni Couture",
      description:
        "Black calf with a cap toe and a buckled strap, made in Italy on a leather sole. It carries navy and charcoal equally.",
    },
  },
  {
    key: "nyoni-chelsea-ii",
    productUrl: "https://nyonicouture.com/product/boots/chelsea-ii/",
    priceUsd: 495,
    image: "/collection/nyoni-chelsea-ii.webp",
    attributes: {
      name: "Chelsea II Boot",
      category: "shoes",
      subcategory: "boots",
      colours: { primary: "black", secondary: [], hex: ["#141414"] },
      pattern: "solid",
      material: "calfskin",
      season: ["autumn", "winter", "spring"],
      formality: "smart-casual",
      brand: "Nyoni Couture",
      description:
        "A black calf Chelsea with a brogued wing-tip, made in Italy. Pulls on, and goes under a suit trouser without a word.",
    },
  },
  {
    key: "nyoni-hamburg-wing-tip",
    productUrl: "https://nyonicouture.com/product/boots/hamburg-wing-tip/",
    priceUsd: 495,
    image: "/collection/nyoni-hamburg-wing-tip.webp",
    attributes: {
      name: "Hamburg Wing-Tip Boot",
      category: "shoes",
      subcategory: "boots",
      colours: { primary: "black", secondary: [], hex: ["#141414"] },
      pattern: "solid",
      material: "calfskin",
      season: ["autumn", "winter", "spring"],
      formality: "smart-casual",
      brand: "Nyoni Couture",
      description:
        "Black calf, side zip, wing-tip toe, made in Italy on a leather sole. The boot for winter tailoring and a long evening.",
    },
  },

  // Pocket squares
  {
    key: "nyoni-silvano-2",
    productUrl: "https://nyonicouture.com/product/accessories/pocket-squares/silvano-2/",
    priceUsd: 69,
    image: "/collection/nyoni-silvano-2.webp",
    attributes: {
      name: "Silvano Pocket Square",
      category: "accessory",
      subcategory: "pocket square",
      colours: { primary: "navy", secondary: [], hex: ["#1F2A44"] },
      pattern: "solid",
      material: "silk",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Navy silk with a fine ivory foliate print, made in Italy. The square for a navy or charcoal suit when the occasion is not about the square.",
    },
  },
  {
    key: "nyoni-paisley",
    productUrl: "https://nyonicouture.com/product/accessories/pocket-squares/paisley/",
    priceUsd: 69,
    image: "/collection/nyoni-paisley.webp",
    attributes: {
      name: "Paisley Pocket Square",
      category: "accessory",
      subcategory: "pocket square",
      colours: { primary: "black", secondary: [], hex: ["#141414"] },
      pattern: "paisley",
      material: "silk",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Black silk with a small ivory paisley, made in Italy. It finishes black tie and charcoal tailoring without raising its voice.",
    },
  },
  {
    key: "nyoni-belagio-2",
    productUrl: "https://nyonicouture.com/product/accessories/pocket-squares/belagio-2/",
    priceUsd: 69,
    image: "/collection/nyoni-belagio-2.webp",
    attributes: {
      name: "Belagio Pocket Square",
      category: "accessory",
      subcategory: "pocket square",
      colours: { primary: "teal", secondary: [], hex: ["#1F6F73"] },
      pattern: "solid",
      material: "silk",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Deep teal paisley on near-black silk, made in Italy. Evening, and the one square here that reads as colour from across a room.",
    },
  },
  {
    key: "nyoni-venez-2",
    productUrl: "https://nyonicouture.com/product/accessories/pocket-squares/venez-2/",
    priceUsd: 69,
    image: "/collection/nyoni-venez-2.webp",
    attributes: {
      name: "Venez Pocket Square",
      category: "accessory",
      subcategory: "pocket square",
      colours: { primary: "orange", secondary: [], hex: ["#C7791E"] },
      pattern: "solid",
      material: "silk",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Copper baroque on black silk, made in Italy. It is the answer to the ochre blazer, and to brown tailoring generally.",
    },
  },
  {
    key: "nyoni-serenata-2",
    productUrl: "https://nyonicouture.com/product/accessories/pocket-squares/serenata-2/",
    priceUsd: 69,
    image: "/collection/nyoni-serenata-2.webp",
    attributes: {
      name: "Serenata Pocket Square",
      category: "accessory",
      subcategory: "pocket square",
      colours: { primary: "blue", secondary: [], hex: ["#3B6EA8"] },
      pattern: "solid",
      material: "silk",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Blue and ivory silk stripe, made in Italy. The square for a patterned jacket, where another pattern would be one too many.",
    },
  },

  // Belts
  {
    key: "nyoni-black-belt-2",
    productUrl: "https://nyonicouture.com/product/uncategorized/black-belt-2/",
    priceUsd: 145,
    image: "/collection/nyoni-black-belt-2.webp",
    attributes: {
      name: "Black Leather Belt",
      category: "accessory",
      subcategory: "belt",
      colours: { primary: "black", secondary: [], hex: ["#141414"] },
      pattern: "solid",
      material: "wool",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "smart-casual",
      brand: "Nyoni Couture",
      description:
        "Black calf with a squared buckle. It is the belt the black and charcoal trousers ask for, and the only one the house stocks.",
    },
  },
];

export function collectionPiece(key: string): CollectionPiece | undefined {
  return COLLECTION.find((piece) => piece.key === key);
}
