import type { Infer } from "convex/values";
import type { vItemAttributes } from "./validators";

/**
 * The Nyoni capsule: the 22 pieces every member's wardrobe starts with, enough to dress a
 * boardroom, a wedding, a black-tie dinner and a Saturday. GENERATED by scripts/build-collection.mjs
 * from research/nyoni/woo-products.json on 2026-09-21; choose the pieces in that
 * script's CAPSULE list, not here. `key` is stable across syncs (it is what `items.collectionKey` stores);
 * a piece whose image cannot be fetched is skipped by the seeder rather than failing the whole seed, and a
 * member's item whose key has left the capsule is retired on their next seed.
 */
export type CollectionPiece = {
  key: string;
  productUrl: string;
  priceUsd?: number;
  image: string;
  attributes: Infer<typeof vItemAttributes>;
};

export const COLLECTION: readonly CollectionPiece[] = [
  // Tailoring
  {
    key: "nyoni-cascata-2",
    productUrl: "https://nyonicouture.com/product/two-piece/cascata-2/",
    priceUsd: 985,
    image: "/collection/nyoni-cascata-2.webp",
    attributes: {
      name: "Midnight Navy Two Piece Suit",
      category: "suit",
      subcategory: "two-piece suit",
      colours: { primary: "navy", secondary: [], hex: ["#1F2A44"] },
      pattern: "solid",
      material: "wool",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      fit: "slim",
      brand: "Nyoni Couture",
      description:
        "The most authoritative color in menswear — with the lapel construction to match. The Nyoni Midnight Navy Peak Two Piece Suit delivers deep midnight navy Super 200s wool through wide peak lapels that make the most commanding blue in formal d",
    },
  },
  {
    key: "nyoni-grayson",
    productUrl: "https://nyonicouture.com/product/three-piece-suit/grayson/",
    priceUsd: 895,
    image: "/collection/nyoni-grayson.webp",
    attributes: {
      name: "Charcoal Three Piece Suit",
      category: "suit",
      subcategory: "three-piece suit",
      colours: { primary: "charcoal", secondary: [], hex: ["#3A3A3A"] },
      pattern: "solid",
      material: "wool",
      season: ["autumn", "winter", "spring"],
      formality: "formal",
      fit: "slim",
      brand: "Nyoni Couture",
      description:
        "The three-piece suit that works everywhere and apologises to no one. The Nyoni Charcoal Three Piece Suit delivers the complete construction authority of three-piece dressing in deep charcoal Super 200s wool — single breasted notch lapel jac",
    },
  },
  {
    key: "nyoni-kijivu-suit",
    productUrl: "https://nyonicouture.com/product/two-piece/kijivu-suit/",
    priceUsd: 895,
    image: "/collection/nyoni-kijivu-suit.webp",
    attributes: {
      name: "Silver Grey Peak Two Piece Suit",
      category: "suit",
      subcategory: "two-piece suit",
      colours: { primary: "grey", secondary: ["silver"], hex: ["#7D7B76"] },
      pattern: "solid",
      material: "wool",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      fit: "slim",
      brand: "Nyoni Couture",
      description:
        "The neutral that answers every room. The Nyoni Silver Grey Peak Two Piece Suit arrives in a clean mid silver-grey Super 200s wool — wide peak lapels that give the most versatile formal neutral the structural presence it deserves, a 2-button",
    },
  },
  {
    key: "nyoni-isabella-bleu-pin-suit",
    productUrl: "https://nyonicouture.com/product/double-breasted/isabella-bleu-pin-suit/",
    priceUsd: 795,
    image: "/collection/nyoni-isabella-bleu-pin-suit.webp",
    attributes: {
      name: "Navy Chalk Stripe Peak Db Suit",
      category: "suit",
      subcategory: "double-breasted suit",
      colours: { primary: "navy", secondary: [], hex: ["#1F2A44"] },
      pattern: "stripe",
      material: "wool",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      fit: "slim",
      brand: "Nyoni Couture",
      description:
        "The suit that wrote the language of power dressing — and hasn't stopped speaking it since. The Nyoni Navy Chalk Stripe Peak Double Breasted Suit brings the most commanding pattern in menswear history to the Nyoni Couture DB collection: navy",
    },
  },
  {
    key: "nyoni-opel-black-tux",
    productUrl: "https://nyonicouture.com/product/tuxedo/opel-black-tux/",
    priceUsd: 895,
    image: "/collection/nyoni-opel-black-tux.webp",
    attributes: {
      name: "Sovereign Black Double-Breasted Tuxedo",
      category: "suit",
      subcategory: "tuxedo",
      colours: { primary: "black", secondary: [], hex: ["#141414"] },
      pattern: "solid",
      material: "wool",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      fit: "slim",
      brand: "Nyoni Couture",
      description:
        "No pattern, no distraction just structure. This double-breasted tuxedo leans entirely on the cut: a satin peak lapel, a six-button front, and a shoulder line built to hold its shape all night. It's understated by design, but the kind of und",
    },
  },

  // Layers
  {
    key: "nyoni-cobalt-blazer-2",
    productUrl: "https://nyonicouture.com/product/blazers/cobalt-blazer-2/",
    priceUsd: 495,
    image: "/collection/nyoni-cobalt-blazer-2.webp",
    attributes: {
      name: "Steel Birdseye Notch Blazer",
      category: "outerwear",
      subcategory: "blazer",
      colours: { primary: "grey", secondary: [], hex: ["#7D7B76"] },
      pattern: "solid",
      material: "wool",
      season: ["spring", "autumn", "winter"],
      formality: "smart-casual",
      fit: "slim",
      brand: "Nyoni Couture",
      description:
        "The blazer that means business — and looks like it enjoys the process. The Nyoni Steel Birdseye Notch Blazer is woven from Super 110s wool in a classic navy-white birdseye weave that reads as a cool, sophisticated steel blue-grey — sharp en",
    },
  },
  {
    key: "nyoni-grey-overcoat",
    productUrl: "https://nyonicouture.com/product/winter-coat/grey-overcoat/",
    priceUsd: 595,
    image: "/collection/nyoni-grey-overcoat.webp",
    attributes: {
      name: "Charcoal Grey Double Breasted Cashmere Overcoat",
      category: "outerwear",
      subcategory: "overcoat",
      colours: { primary: "grey", secondary: ["charcoal"], hex: ["#7D7B76"] },
      pattern: "solid",
      material: "cashmere",
      season: ["autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Charcoal Grey. Peak Lapel. Double Breasted. The Overcoat That Goes With Everything. The most essential piece in the range. The Nyoni Charcoal Grey Double Breasted Cashmere Overcoat is built in 100% Cashmere in deep charcoal — the most unive",
    },
  },

  // Trousers
  {
    key: "nyoni-classic-side-adjuster-dress-pants",
    productUrl: "https://nyonicouture.com/product/trousers/nyoni-classic-side-adjuster-dress-pants/",
    priceUsd: 195,
    image: "/collection/nyoni-classic-side-adjuster-dress-pants.webp",
    attributes: {
      name: "Classic Side Adjuster Dress Pants",
      category: "bottom",
      subcategory: "dress trousers",
      colours: { primary: "black", secondary: [], hex: ["#141414"] },
      pattern: "solid",
      material: "wool",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "A timeless wardrobe essential, these Classic Black Side Adjuster Dress Pants are expertly tailored for the modern gentleman. Crafted from premium suiting fabric, they feature a sleek flat-front design with elegant side adjusters, creating a",
    },
  },
  {
    key: "nyoni-midnight-glen-plaid-pant",
    productUrl: "https://nyonicouture.com/product/trousers/nyoni-midnight-glen-plaid-pant/",
    priceUsd: 195,
    image: "/collection/nyoni-midnight-glen-plaid-pant.webp",
    attributes: {
      name: "Midnight Glen Plaid Pant",
      category: "bottom",
      subcategory: "dress trousers",
      colours: { primary: "navy", secondary: [], hex: ["#1F2A44"] },
      pattern: "glen plaid",
      material: "wool",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Nyoni Midnight Glen Plaid Trousers feature a stylish plaid design with a comfortable fit, ideal for versatile wear in both formal and casual settings.",
    },
  },
  {
    key: "nyoni-taupe-flat-front-tailored-dress-pants",
    productUrl: "https://nyonicouture.com/product/trousers/nyoni-taupe-flat-front-tailored-dress-pants/",
    priceUsd: 265,
    image: "/collection/nyoni-taupe-flat-front-tailored-dress-pants.webp",
    attributes: {
      name: "Taupe Flat Front Tailored Dress Pants",
      category: "bottom",
      subcategory: "dress trousers",
      colours: { primary: "taupe", secondary: [], hex: ["#B3A492"] },
      pattern: "solid",
      material: "wool",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Refined, versatile, and effortlessly sophisticated, these Taupe Flat Front Tailored Dress Pants are a timeless essential for every modern gentleman’s wardrobe. Crafted from premium suiting fabric, they feature a clean flat-front design and ",
    },
  },

  // Shirts and knitwear
  {
    key: "nyoni-cavalera-formal",
    productUrl: "https://nyonicouture.com/product/dress-shirts/cavalera-formal/",
    priceUsd: 129,
    image: "/collection/nyoni-cavalera-formal.webp",
    attributes: {
      name: "Classic Tuxedo Shirt",
      category: "top",
      subcategory: "dress shirt",
      colours: { primary: "white", secondary: [], hex: ["#F7F5F0"] },
      pattern: "solid",
      material: "cotton",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description: "Tux Shirt Collar Long sleeves French Cuffs Cotton Dry clean Imported",
    },
  },
  {
    key: "nyoni-elna-blu",
    productUrl: "https://nyonicouture.com/product/dress-shirts/elna-blu/",
    priceUsd: 149,
    image: "/collection/nyoni-elna-blu.webp",
    attributes: {
      name: "Elna Blue Spread Collar Shirt",
      category: "top",
      subcategory: "dress shirt",
      colours: { primary: "blue", secondary: [], hex: ["#3B6EA8"] },
      pattern: "solid",
      material: "cotton",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Spread collar; button placket Long sleeves Round barrel interchangeable button or French cuffs Cotton Dry clean Imported",
    },
  },
  {
    key: "nyoni-sable-black-spread-collar-shirt",
    productUrl: "https://nyonicouture.com/product/dress-shirts/nyoni-sable-black-spread-collar-shirt/",
    priceUsd: 129,
    image: "/collection/nyoni-sable-black-spread-collar-shirt.webp",
    attributes: {
      name: "Sable Black Spread Collar Shirt",
      category: "top",
      subcategory: "dress shirt",
      colours: { primary: "black", secondary: [], hex: ["#141414"] },
      pattern: "solid",
      material: "cotton",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Spread collar; button placket Long sleeves Round barrel interchangeable button or French cuffs Cotton Dry clean Imported",
    },
  },
  {
    key: "nyoni-navy-turtleneck",
    productUrl: "https://nyonicouture.com/product/sweater/nyoni-navy-turtleneck/",
    priceUsd: 89,
    image: "/collection/nyoni-navy-turtleneck.webp",
    attributes: {
      name: "Navy Turtleneck",
      category: "top",
      subcategory: "sweater",
      colours: { primary: "navy", secondary: [], hex: ["#1F2A44"] },
      pattern: "solid",
      material: "wool",
      season: ["autumn", "winter"],
      formality: "smart-casual",
      brand: "Nyoni Couture",
      description:
        "The Nyoni Navy Turtleneck combines a cozy design with a versatile style, making it suitable for various occasions. Crafted from luxurious fabric, it ensures both comfort and sophistication.",
    },
  },
  {
    key: "nyoni-kenzie",
    productUrl: "https://nyonicouture.com/product/accessories/vest/kenzie/",
    priceUsd: 186,
    image: "/collection/nyoni-kenzie.webp",
    attributes: {
      name: "Kenzie Waistcoat",
      category: "top",
      subcategory: "waistcoat",
      colours: { primary: "navy", secondary: [], hex: ["#1F2A44"] },
      pattern: "solid",
      material: "wool",
      season: ["autumn", "winter", "spring"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "A navy wool waistcoat for separates: over the blue shirt with grey or taupe trousers, or under the blazer when the evening turns formal.",
    },
  },

  // Shoes
  {
    key: "nyoni-oxford",
    productUrl: "https://nyonicouture.com/product/dress-shoes/oxford/",
    priceUsd: 525,
    image: "/collection/nyoni-oxford.webp",
    attributes: {
      name: "Oxford",
      category: "shoes",
      subcategory: "dress shoes",
      colours: { primary: "black", secondary: [], hex: ["#141414"] },
      pattern: "solid",
      material: "leather",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "The black cap-toe oxford, the one shoe that answers every suit in the capsule and carries black tie when the evening calls for it.",
    },
  },
  {
    key: "nyoni-monaco-cap-toe",
    productUrl: "https://nyonicouture.com/product/boots/monaco-cap-toe/",
    priceUsd: 550,
    image: "/collection/nyoni-monaco-cap-toe.webp",
    attributes: {
      name: "Monaco Cap-Toe Boot",
      category: "shoes",
      subcategory: "boots",
      colours: { primary: "black", secondary: [], hex: ["#141414"] },
      pattern: "solid",
      material: "suede",
      season: ["autumn", "winter", "spring"],
      formality: "smart-casual",
      brand: "Nyoni Couture",
      description:
        "Exclusively Ours. ( Bismack Biyombo Luxury Boot ) Black calfskin black suede elastic black calfskin lining Genuine Leather sole, bottom in natural brushed leather Genuine leather inner-sole 100% made in Italy ACCESSORY: /// PACKAGING: box c",
    },
  },
  {
    key: "nyoni-florence-ii-penny-loafer",
    productUrl: "https://nyonicouture.com/product/loafers/florence-ii-penny-loafer/",
    priceUsd: 450,
    image: "/collection/nyoni-florence-ii-penny-loafer.webp",
    attributes: {
      name: "Florence II Penny Loafer",
      category: "shoes",
      subcategory: "loafers",
      colours: { primary: "burgundy", secondary: [], hex: ["#5E1B2A"] },
      pattern: "solid",
      material: "calfskin",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "smart-casual",
      brand: "Nyoni Couture",
      description:
        "Exclusively Ours. (Bismack Biyombo Luxury Penny Loafers) Burgundy bright calfskin Lining: Black calfskin Sole: Genuine Leather Sole, bottom in black color Innersole: Genuine leather 100% made in Italy PACKAGING: box covered with prestigious",
    },
  },

  // Accessories
  {
    key: "nyoni-obinna",
    productUrl: "https://nyonicouture.com/product/accessories/neck-tie/obinna/",
    priceUsd: 95,
    image: "/collection/nyoni-obinna.webp",
    attributes: {
      name: "Obina Stripe Neck-tie",
      category: "accessory",
      subcategory: "neck tie",
      colours: { primary: "teal", secondary: [], hex: ["#1F6F73"] },
      pattern: "stripe",
      material: "wool",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "A handcrafted Milano silk tie, teal ground with a grey bar stripe: the pattern that sits comfortably against navy, charcoal and grey.",
    },
  },
  {
    key: "nyoni-granito-2",
    productUrl: "https://nyonicouture.com/product/accessories/neck-tie/granito-2/",
    priceUsd: 95,
    image: "/collection/nyoni-granito-2.webp",
    attributes: {
      name: "Granito Silk Neck-tie",
      category: "accessory",
      subcategory: "neck tie",
      colours: { primary: "blue", secondary: [], hex: ["#3B6EA8"] },
      pattern: "geo",
      material: "silk",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "Geometric Silk Tie – NYONI Couture Make a refined statement with this silk tie, crafted for the modern gentleman who appreciates detail and distinction. Featuring an intricate geometric pattern, this design adds subtle texture and depth whi",
    },
  },
  {
    key: "nyoni-brittan-2",
    productUrl: "https://nyonicouture.com/product/accessories/bow-tie/brittan-2/",
    priceUsd: 69,
    image: "/collection/nyoni-brittan-2.webp",
    attributes: {
      name: "Brittan Silk Bow Tie",
      category: "accessory",
      subcategory: "bow tie",
      colours: { primary: "black", secondary: [], hex: ["#141414"] },
      pattern: "solid",
      material: "silk",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description: "The black silk self-tie bow. Black tie asks for one thing, and this is it.",
    },
  },
  {
    key: "nyoni-silvano-2",
    productUrl: "https://nyonicouture.com/product/accessories/pocket-squares/silvano-2/",
    priceUsd: 69,
    image: "/collection/nyoni-silvano-2.webp",
    attributes: {
      name: "Silvano Pocket Square",
      category: "accessory",
      subcategory: "pocket square",
      colours: { primary: "navy", secondary: [], hex: ["#1F2A44"] },
      pattern: "solid",
      material: "silk",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "formal",
      brand: "Nyoni Couture",
      description:
        "A navy silk pocket square with a fine white print, made in Italy. Restrained enough for the boardroom, finished enough for a wedding.",
    },
  },
];

export function collectionPiece(key: string): CollectionPiece | undefined {
  return COLLECTION.find((piece) => piece.key === key);
}
