/**
 * Fictional fixture data for the front end, so every screen can be built and reviewed before the
 * Convex backend exists. The products, prices and photography are Nyoni Couture's own; the member,
 * her orders, appointments, wears and conversations are invented and must never be presented as
 * real people or real transactions. Replaced table by table as each backend milestone lands.
 */

import type {
  Appointment,
  BagLine,
  Conversation,
  Drop,
  Look,
  Message,
  Order,
  Piece,
  Preview,
  Product,
  Showroom,
  SuitEntitlement,
  Wear,
} from "./types";

export const products: Product[] = [
  {
    id: "nyoni-cascata-2",
    name: "Midnight Navy Two Piece Suit",
    priceUsd: 985,
    category: "suit",
    subcategory: "two-piece suit",
    colour: "navy",
    pattern: "solid",
    material: "wool",
    formality: "formal",
    permalink: "https://nyonicouture.com/product/two-piece/cascata-2/",
    variations: [
      { size: "38R", inStock: true },
      { size: "40R", inStock: false },
      { size: "42R", inStock: true },
      { size: "44R", inStock: true },
      { size: "46R", inStock: true },
    ],
  },
  {
    id: "nyoni-grayson",
    name: "Charcoal Three Piece Suit",
    priceUsd: 895,
    category: "suit",
    subcategory: "three-piece suit",
    colour: "charcoal",
    pattern: "solid",
    material: "wool",
    formality: "formal",
    permalink: "https://nyonicouture.com/product/three-piece-suit/grayson/",
    variations: [
      { size: "38R", inStock: true },
      { size: "40R", inStock: true },
      { size: "42R", inStock: true },
      { size: "44R", inStock: true },
      { size: "46R", inStock: true },
    ],
  },
  {
    id: "nyoni-kijivu-suit",
    name: "Silver Grey Peak Two Piece Suit",
    priceUsd: 895,
    category: "suit",
    subcategory: "two-piece suit",
    colour: "grey",
    pattern: "solid",
    material: "wool",
    formality: "formal",
    permalink: "https://nyonicouture.com/product/two-piece/kijivu-suit/",
    variations: [
      { size: "38R", inStock: true },
      { size: "40R", inStock: true },
      { size: "42R", inStock: true },
      { size: "44R", inStock: true },
      { size: "46R", inStock: true },
    ],
  },
  {
    id: "nyoni-isabella-bleu-pin-suit",
    name: "Navy Chalk Stripe Peak Db Suit",
    priceUsd: 795,
    category: "suit",
    subcategory: "double-breasted suit",
    colour: "navy",
    pattern: "stripe",
    material: "wool",
    formality: "formal",
    permalink: "https://nyonicouture.com/product/double-breasted/isabella-bleu-pin-suit/",
    variations: [
      { size: "38R", inStock: true },
      { size: "40R", inStock: true },
      { size: "42R", inStock: true },
      { size: "44R", inStock: true },
      { size: "46R", inStock: true },
    ],
  },
  {
    id: "nyoni-opel-black-tux",
    name: "Sovereign Black Double-Breasted Tuxedo",
    priceUsd: 895,
    category: "suit",
    subcategory: "tuxedo",
    colour: "black",
    pattern: "solid",
    material: "wool",
    formality: "formal",
    permalink: "https://nyonicouture.com/product/tuxedo/opel-black-tux/",
    variations: [
      { size: "38R", inStock: true },
      { size: "40R", inStock: true },
      { size: "42R", inStock: true },
      { size: "44R", inStock: true },
      { size: "46R", inStock: true },
    ],
  },
  {
    id: "nyoni-cobalt-blazer-2",
    name: "Steel Birdseye Notch Blazer",
    priceUsd: 495,
    category: "outerwear",
    subcategory: "blazer",
    colour: "grey",
    pattern: "solid",
    material: "wool",
    formality: "smart-casual",
    permalink: "https://nyonicouture.com/product/blazers/cobalt-blazer-2/",
    variations: [
      { size: "S", inStock: true },
      { size: "M", inStock: true },
      { size: "L", inStock: true },
      { size: "XL", inStock: true },
    ],
  },
  {
    id: "nyoni-grey-overcoat",
    name: "Charcoal Grey Double Breasted Cashmere Overcoat",
    priceUsd: 595,
    category: "outerwear",
    subcategory: "overcoat",
    colour: "grey",
    pattern: "solid",
    material: "cashmere",
    formality: "formal",
    permalink: "https://nyonicouture.com/product/winter-coat/grey-overcoat/",
    variations: [
      { size: "S", inStock: true },
      { size: "M", inStock: true },
      { size: "L", inStock: true },
      { size: "XL", inStock: true },
    ],
  },
  {
    id: "nyoni-classic-side-adjuster-dress-pants",
    name: "Classic Side Adjuster Dress Pants",
    priceUsd: 195,
    category: "bottom",
    subcategory: "dress trousers",
    colour: "black",
    pattern: "solid",
    material: "wool",
    formality: "formal",
    permalink: "https://nyonicouture.com/product/trousers/nyoni-classic-side-adjuster-dress-pants/",
    variations: [
      { size: "30", inStock: true },
      { size: "32", inStock: false },
      { size: "34", inStock: true },
      { size: "36", inStock: true },
      { size: "38", inStock: true },
    ],
  },
  {
    id: "nyoni-midnight-glen-plaid-pant",
    name: "Midnight Glen Plaid Pant",
    priceUsd: 195,
    category: "bottom",
    subcategory: "dress trousers",
    colour: "navy",
    pattern: "glen plaid",
    material: "wool",
    formality: "formal",
    permalink: "https://nyonicouture.com/product/trousers/nyoni-midnight-glen-plaid-pant/",
    variations: [
      { size: "30", inStock: true },
      { size: "32", inStock: true },
      { size: "34", inStock: true },
      { size: "36", inStock: true },
      { size: "38", inStock: true },
    ],
  },
  {
    id: "nyoni-taupe-flat-front-tailored-dress-pants",
    name: "Taupe Flat Front Tailored Dress Pants",
    priceUsd: 265,
    category: "bottom",
    subcategory: "dress trousers",
    colour: "taupe",
    pattern: "solid",
    material: "wool",
    formality: "formal",
    permalink: "https://nyonicouture.com/product/trousers/nyoni-taupe-flat-front-tailored-dress-pants/",
    variations: [
      { size: "30", inStock: true },
      { size: "32", inStock: true },
      { size: "34", inStock: true },
      { size: "36", inStock: true },
      { size: "38", inStock: true },
    ],
  },
  {
    id: "nyoni-cavalera-formal",
    name: "Classic Tuxedo Shirt",
    priceUsd: 129,
    category: "top",
    subcategory: "dress shirt",
    colour: "white",
    pattern: "solid",
    material: "cotton",
    formality: "formal",
    permalink: "https://nyonicouture.com/product/dress-shirts/cavalera-formal/",
    variations: [
      { size: "15/33", inStock: true },
      { size: "15.5/34", inStock: true },
      { size: "16/34", inStock: true },
      { size: "16.5/35", inStock: true },
      { size: "17/35", inStock: true },
    ],
  },
  {
    id: "nyoni-elna-blu",
    name: "Elna Blue Spread Collar Shirt",
    priceUsd: 149,
    category: "top",
    subcategory: "dress shirt",
    colour: "blue",
    pattern: "solid",
    material: "cotton",
    formality: "formal",
    permalink: "https://nyonicouture.com/product/dress-shirts/elna-blu/",
    variations: [
      { size: "15/33", inStock: true },
      { size: "15.5/34", inStock: true },
      { size: "16/34", inStock: true },
      { size: "16.5/35", inStock: true },
      { size: "17/35", inStock: true },
    ],
  },
  {
    id: "nyoni-sable-black-spread-collar-shirt",
    name: "Sable Black Spread Collar Shirt",
    priceUsd: 129,
    category: "top",
    subcategory: "dress shirt",
    colour: "black",
    pattern: "solid",
    material: "cotton",
    formality: "formal",
    permalink: "https://nyonicouture.com/product/dress-shirts/nyoni-sable-black-spread-collar-shirt/",
    variations: [
      { size: "15/33", inStock: true },
      { size: "15.5/34", inStock: true },
      { size: "16/34", inStock: true },
      { size: "16.5/35", inStock: true },
      { size: "17/35", inStock: true },
    ],
  },
  {
    id: "nyoni-navy-turtleneck",
    name: "Navy Turtleneck",
    priceUsd: 89,
    category: "top",
    subcategory: "sweater",
    colour: "navy",
    pattern: "solid",
    material: "wool",
    formality: "smart-casual",
    permalink: "https://nyonicouture.com/product/sweater/nyoni-navy-turtleneck/",
    variations: [
      { size: "15/33", inStock: true },
      { size: "15.5/34", inStock: true },
      { size: "16/34", inStock: true },
      { size: "16.5/35", inStock: true },
      { size: "17/35", inStock: true },
    ],
  },
  {
    id: "nyoni-kenzie",
    name: "Kenzie Waistcoat",
    priceUsd: 186,
    category: "top",
    subcategory: "waistcoat",
    colour: "navy",
    pattern: "solid",
    material: "wool",
    formality: "formal",
    permalink: "https://nyonicouture.com/product/accessories/vest/kenzie/",
    variations: [
      { size: "15/33", inStock: true },
      { size: "15.5/34", inStock: false },
      { size: "16/34", inStock: true },
      { size: "16.5/35", inStock: true },
      { size: "17/35", inStock: true },
    ],
  },
  {
    id: "nyoni-oxford",
    name: "Oxford",
    priceUsd: 525,
    category: "shoes",
    subcategory: "dress shoes",
    colour: "black",
    pattern: "solid",
    material: "leather",
    formality: "formal",
    permalink: "https://nyonicouture.com/product/dress-shoes/oxford/",
    variations: [
      { size: "8", inStock: true },
      { size: "9", inStock: true },
      { size: "10", inStock: true },
      { size: "11", inStock: true },
      { size: "12", inStock: true },
    ],
  },
  {
    id: "nyoni-monaco-cap-toe",
    name: "Monaco Cap-Toe Boot",
    priceUsd: 550,
    category: "shoes",
    subcategory: "boots",
    colour: "black",
    pattern: "solid",
    material: "suede",
    formality: "smart-casual",
    permalink: "https://nyonicouture.com/product/boots/monaco-cap-toe/",
    variations: [
      { size: "8", inStock: true },
      { size: "9", inStock: true },
      { size: "10", inStock: true },
      { size: "11", inStock: true },
      { size: "12", inStock: true },
    ],
  },
  {
    id: "nyoni-florence-ii-penny-loafer",
    name: "Florence II Penny Loafer",
    priceUsd: 450,
    category: "shoes",
    subcategory: "loafers",
    colour: "burgundy",
    pattern: "solid",
    material: "calfskin",
    formality: "smart-casual",
    permalink: "https://nyonicouture.com/product/loafers/florence-ii-penny-loafer/",
    variations: [
      { size: "8", inStock: true },
      { size: "9", inStock: true },
      { size: "10", inStock: true },
      { size: "11", inStock: true },
      { size: "12", inStock: true },
    ],
  },
  {
    id: "nyoni-obinna",
    name: "Obina Stripe Neck-tie",
    priceUsd: 95,
    category: "accessory",
    subcategory: "neck tie",
    colour: "teal",
    pattern: "stripe",
    material: "wool",
    formality: "formal",
    permalink: "https://nyonicouture.com/product/accessories/neck-tie/obinna/",
    variations: [{ size: "One size", inStock: true }],
  },
  {
    id: "nyoni-granito-2",
    name: "Granito Silk Neck-tie",
    priceUsd: 95,
    category: "accessory",
    subcategory: "neck tie",
    colour: "blue",
    pattern: "geo",
    material: "silk",
    formality: "formal",
    permalink: "https://nyonicouture.com/product/accessories/neck-tie/granito-2/",
    variations: [{ size: "One size", inStock: true }],
  },
  {
    id: "nyoni-brittan-2",
    name: "Brittan Silk Bow Tie",
    priceUsd: 69,
    category: "accessory",
    subcategory: "bow tie",
    colour: "black",
    pattern: "solid",
    material: "silk",
    formality: "formal",
    permalink: "https://nyonicouture.com/product/accessories/bow-tie/brittan-2/",
    variations: [{ size: "One size", inStock: true }],
  },
  {
    id: "nyoni-silvano-2",
    name: "Silvano Pocket Square",
    priceUsd: 69,
    category: "accessory",
    subcategory: "pocket square",
    colour: "navy",
    pattern: "solid",
    material: "silk",
    formality: "formal",
    permalink: "https://nyonicouture.com/product/accessories/pocket-squares/silvano-2/",
    variations: [{ size: "One size", inStock: true }],
  },
];

export function productById(id: string): Product | undefined {
  return products.find((product) => product.id === id);
}

export function productsByCategory(category: Product["category"]): Product[] {
  return products.filter((product) => product.category === category);
}
